-- Supabase / Postgres schema for the AI Lead Generation System.
-- Apply once: `npm run migrate:supabase` (also copies local data), or paste
-- this into the Supabase dashboard SQL editor.
--
-- IDs use GENERATED BY DEFAULT AS IDENTITY so the data migration can preserve
-- existing row ids (keeping outreach -> lead links intact) while normal app
-- inserts still auto-assign ids.

create table if not exists leads (
  id integer generated by default as identity primary key,
  name text not null,
  website text not null,
  phone text default '',
  email text default '',
  address text default '',
  industry text default '',
  location text default '',
  source text default '',
  design_score integer default 0,
  seo_score integer default 0,
  conversion_score integer default 0,
  lead_score integer default 0,
  priority text default 'LOW',
  status text default 'new',
  ai_summary text default '',
  issues text default '[]',
  opportunities text default '[]',
  engine text default 'fallback',
  web_presence text not null default 'site',
  priority_locked integer not null default 0,
  meta text,
  created_at timestamptz default now()
);

-- A website should only ever produce one lead row.
create unique index if not exists idx_leads_website on leads (website);
create index if not exists idx_leads_priority on leads (priority);
create index if not exists idx_leads_status on leads (status);
create index if not exists idx_leads_web_presence on leads (web_presence);

create table if not exists outreach (
  id integer generated by default as identity primary key,
  lead_id integer not null references leads (id) on delete cascade,
  type text not null,
  message text not null,
  sent integer default 0,
  created_at timestamptz default now()
);
create index if not exists idx_outreach_lead on outreach (lead_id);

create table if not exists scan_jobs (
  id integer generated by default as identity primary key,
  industry text default '',
  location text default '',
  status text default 'running',
  found integer default 0,
  scraped integer default 0,
  failed integer default 0,
  created_at timestamptz default now()
);

create table if not exists settings (
  key text primary key,
  value text not null
);

-- Lock down the public Data API. The app connects via a direct Postgres
-- connection (a privileged role that bypasses RLS), but enabling RLS with NO
-- policies blocks the anon/authenticated roles from reaching these tables over
-- Supabase's auto-generated REST API. Important because the publishable key is
-- effectively public.
alter table leads enable row level security;
alter table outreach enable row level security;
alter table scan_jobs enable row level security;
alter table settings enable row level security;
